name: Complex workflow - Main branch
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
    secrets:
      github-private-actions-pat:
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false


jobs:
  build:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@0.1.0
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  deploy:
    runs-on: ["self-hosted"]
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.1.0
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'environments/'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: dev
          namespace: dev

      - name: Deploy
        uses: cloudposse/github-action-deploy-helmfile@0.1.0
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          base-role: ${{ steps.environment.outputs.role }}
          cluster: ${{ steps.environment.outputs.cluster }}
          cluster-role: ${{ steps.environment.outputs.cluster-role }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ needs.build.outputs.image }}
          image-tag: ${{ needs.build.outputs.tag }}
          operation: deploy

  draft_release:
    name: draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [ deploy ]
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
