name: Dockerized Appication - Release
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
      version:
        required: true
        type: string
    secrets:
      docker-login:
        required: true
      docker-password:
        required: true
      github-private-actions-pat:
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  promote:
    runs-on: ["self-hosted"]
    permissions:
      contents: write
    steps:
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.docker-login }}
          password: ${{ secrets.docker-password }}

      - name: Promote Docker image
        uses: EuphoricSystems/docker-promote-image@1.0.0
        with:
          src: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:sha-${{ github.sha }}
          destinations: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:${{ github.event.release.tag_name }}

    outputs:
      image: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
      tag: ${{ github.event.release.tag_name }}

  deploy_staging:
    runs-on: ["self-hosted"]
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ promote ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.1.0
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'environments/'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: staging
          namespace: staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          role-to-assume: ${{ steps.environment.outputs.cluster-role }}
          role-session-name: deploy

      - name: Deploy
        id: deploy
        uses: cloudposse/github-action-deploy-helmfile@0.2.0
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          cluster: ${{ steps.environment.outputs.cluster }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ needs.promote.outputs.image }}
          image-tag: ${{ needs.promote.outputs.tag }}
          operation: deploy
        env:
          ISTIO_INSTALLED: false
          COLOR: green
          RELEASE_NAME: example-app-green

  deploy_production:
    runs-on: ["self-hosted"]
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ promote, deploy_staging ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.1.0
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'environments/'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: production
          namespace: production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          role-to-assume: ${{ steps.environment.outputs.cluster-role }}
          role-session-name: deploy

      - name: Deploy
        id: deploy
        uses: cloudposse/github-action-deploy-helmfile@0.2.0
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          cluster: ${{ steps.environment.outputs.cluster }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ needs.promote.outputs.image }}
          image-tag: ${{ needs.promote.outputs.tag }}
          operation: deploy
        env:
          ISTIO_INSTALLED: false
          COLOR: green
          RELEASE_NAME: example-app-green